#!/usr/bin/env python3
"""
gen_stubs.py — generate jump-thunk forwarding stubs for the dbghelp proxy DLL.

Reads the export table of a reference dbghelp.dll (via `winedump -j export`)
and emits three files used by build.sh:

  src/stubs.h    — extern declarations of the cached pointers and the
                    per-export lookup table consumed by DllMain
  src/stubs.c    — definitions of the cached pointers, the lookup table,
                    and one C forwarder function per export
  src/dbghelp.def — EXPORTS section listing every forwarded name

Design notes
------------
The stubs use the standard proxy-DLL pattern:

    void SymInitialize(void) {
        FARPROC p = g_fwd_SymInitialize;
        if (!p) p = g_fwd_SymInitialize = fwd_resolve("SymInitialize");
        ((void(*)(void))p)();
    }

The cached pointer is populated eagerly by DllMain (so the lazy path is
just a safety net). On the fast path GCC compiles this to a 2-instruction
tail jump (`mov rax,[rip+ptr]; jmp rax`), which preserves all argument
registers (RCX/RDX/R8/R9/XMM0-3) and the original caller's shadow space.
The forwarded function sees exactly the same call frame it would have seen
had it been called directly. No per-export signature knowledge required.

The lazy path clobbers argument registers (it has to call GetProcAddress),
but it only ever fires if DllMain failed to resolve that specific export —
which we treat as a soft failure (logged) rather than crash the process.
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path

# Export-name pattern: alnum + underscore. Filters out "<by ordinal>" noise.
EXPORT_NAME_RE = re.compile(r"^\s*[0-9A-Fa-f]+\s+\d+\s+([A-Za-z_][A-Za-z0-9_]*)\s*$")


def parse_exports(reference_dll: str, winedump: str):
    """Return a list of export names (deduplicated, order-preserving)."""
    out = subprocess.check_output(
        [winedump, "-j", "export", reference_dll],
        stderr=subprocess.STDOUT,
        text=True,
    )
    seen = set()
    names = []
    for line in out.splitlines():
        m = EXPORT_NAME_RE.match(line)
        if not m:
            continue
        name = m.group(1)
        if name in seen:
            continue
        seen.add(name)
        names.append(name)
    return names


def emit_stubs_h(names, out_path: Path):
    lines = [
        "/* AUTO-GENERATED by tools/gen_stubs.py — DO NOT EDIT BY HAND. */",
        "#ifndef DBGHELP_PROXY_STUBS_H",
        "#define DBGHELP_PROXY_STUBS_H",
        "",
        "#include <windows.h>",
        "",
        "/* Resolve an export by name against the real dbghelp.dll.",
        " * Implemented in dllmain.c. Returns NULL if the real DLL is",
        " * not loaded or the export is absent. */",
        "FARPROC fwd_resolve(const char *name);",
        "",
        "/* Cached function pointers (populated by DllMain at attach). */",
        "",
    ]
    for n in names:
        lines.append(f"extern FARPROC g_fwd_{n};")
    lines.append("")
    lines.append("/* Lookup table consumed by DllMain for eager resolution.")
    lines.append(" * Terminated by a sentinel {NULL, NULL}. */")
    lines.append("struct fwd_entry { const char *name; FARPROC *slot; };")
    lines.append("extern const struct fwd_entry g_fwd_entries[];")
    lines.append("")
    lines.append("#endif /* DBGHELP_PROXY_STUBS_H */")
    lines.append("")
    out_path.write_text("\n".join(lines))


def emit_stubs_c(names, out_path: Path):
    lines = [
        "/* AUTO-GENERATED by tools/gen_stubs.py — DO NOT EDIT BY HAND. */",
        "/* dbghelp proxy DLL: jump-thunk forwarders.",
        " *",
        " * This file contains:",
        " *   - definitions of the cached forwarder pointers (g_fwd_<NAME>)",
        " *   - the g_fwd_entries[] lookup table",
        " *   - one C forwarder function per export",
        " */",
        "",
        '#include "stubs.h"',
        "",
        "/* ---- Cached pointers (zero-initialized, populated by DllMain) --- */",
        "",
    ]
    for n in names:
        lines.append(f"FARPROC g_fwd_{n} = NULL;")
    lines.append("")
    lines.append("/* ---- Lookup table for eager resolution in DllMain ---------- */")
    lines.append("")
    lines.append("const struct fwd_entry g_fwd_entries[] = {")
    for n in names:
        lines.append(f'    {{"{n}", &g_fwd_{n}}},')
    lines.append("    {NULL, NULL},")
    lines.append("};")
    lines.append("")
    lines.append("/* ---- Forwarder functions ------------------------------------- */")
    lines.append("/*")
    lines.append(" * Fast path (cache hit):")
    lines.append(" *     mov rax, [rip + g_fwd_<NAME>]")
    lines.append(" *     test rax, rax")
    lines.append(" *     jmp rax")
    lines.append(" * Argument registers (RCX/RDX/R8/R9/XMM0-3) and shadow space")
    lines.append(" * are untouched, so the forwarded function observes the")
    lines.append(" * caller's original frame.")
    lines.append(" */")
    lines.append("")
    for n in names:
        lines.append(f"void {n}(void) {{")
        lines.append(f"    FARPROC p = g_fwd_{n};")
        lines.append(f'    if (!p) p = g_fwd_{n} = fwd_resolve("{n}");')
        lines.append(f"    if (!p) return;  /* real dbghelp missing this export */")
        lines.append("    ((void(*)(void))p)();")
        lines.append("}")
        lines.append("")
    out_path.write_text("\n".join(lines))


def emit_def(names, out_path: Path, machine_label: str):
    lines = [
        "; AUTO-GENERATED by tools/gen_stubs.py",
        f"; {len(names)} forwarded exports from reference dbghelp ({machine_label})",
        "",
        "LIBRARY dbghelp.dll",
        "EXPORTS",
    ]
    for i, n in enumerate(names, start=1):
        # Map each forwarded name to the like-named stub function in stubs.c.
        # Preserve monotonically-increasing ordinals (base 1) so any consumer
        # that imports by ordinal also resolves correctly. NONAME tells the
        # linker to export by both name and ordinal; the .def's primary effect
        # is to make every name available.
        lines.append(f"{n} = {n} @ {i}")
    out_path.write_text("\n".join(lines) + "\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--winedump", default="winedump",
                    help="path to winedump (default: PATH)")
    ap.add_argument("--reference", required=True,
                    help="reference dbghelp.dll to enumerate exports from")
    ap.add_argument("--out-dir", required=True,
                    help="directory to write stubs.h, stubs.c, dbghelp.def")
    args = ap.parse_args()

    names = parse_exports(args.reference, args.winedump)
    if not names:
        print(f"gen_stubs: no exports parsed from {args.reference}", file=sys.stderr)
        sys.exit(1)

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    emit_stubs_h(names, out_dir / "stubs.h")
    emit_stubs_c(names, out_dir / "stubs.c")
    emit_def(names, out_dir / "dbghelp.def", Path(args.reference).name)

    print(f"gen_stubs: wrote {len(names)} exports -> {out_dir}/")
    print(f"  {out_dir/'stubs.h'}")
    print(f"  {out_dir/'stubs.c'}")
    print(f"  {out_dir/'dbghelp.def'}")


if __name__ == "__main__":
    main()
