using System.Text;
using System.Text.Json;
using Magos.Modificus.Config;
using Microsoft.Extensions.Logging;

namespace Magos.Modificus.Profiles;

/// <summary>
/// Filesystem-backed <see cref="IProfileService"/>. Each profile lives under
/// <c>&lt;ProfilesBaseFolder&gt;/&lt;guid&gt;/</c> with this layout:
/// </summary>
/// <remarks>
/// <code>
/// &lt;ProfilesBaseFolder&gt;/          (auto-created on first run)
///   &lt;guid&gt;/                        (profile dir; id-named)
///     profile.json                   (metadata + mod list — the source of truth)
///     mods/                          (the profile's mod root — the --mod-path)
///       mods.lst                     (generated by PrepareModRoot; a projection)
///       &lt;mod-folder&gt;/              (a mod's files, when installed)
/// </code>
/// <para>
/// Registered as a singleton: the service holds no per-request state — all
/// state lives on disk, and <see cref="MagosConfig"/> (its only config source)
/// is itself a singleton. Concurrent writes to the same profile are not
/// coordinated in Phase 1 (single-UI-thread assumption); Phase 2's storage
/// rewrite revisits concurrency if needed.
/// </para>
/// </summary>
internal sealed class ProfileService : IProfileService
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
    };

    // mods.lst is UTF-8 without BOM (the Lua loader reads it line-by-line; a
    // BOM would surface as a stray prefix on the first mod name).
    private static readonly Encoding ModListEncoding = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false);

    private readonly string _baseFolder;
    private readonly ILogger<ProfileService> _logger;

    public ProfileService(MagosConfig config, ILogger<ProfileService> logger)
    {
        // ProfilesBaseFolder is non-null by MagosConfig contract (defaults to
        // &lt;app-data&gt;/profiles). Directory.CreateDirectory is idempotent, so this
        // makes every subsequent op first-run safe without each one re-checking.
        _baseFolder = config.ProfilesBaseFolder;
        _logger = logger;
        Directory.CreateDirectory(_baseFolder);
    }

    /// <inheritdoc />
    public IReadOnlyList<ProfileSummary> ListProfiles()
    {
        var summaries = new List<ProfileSummary>();
        foreach (var dir in Directory.EnumerateDirectories(_baseFolder))
        {
            var name = Path.GetFileName(dir);
            if (!Guid.TryParse(name, out var id))
            {
                _logger.LogDebug("Skipping non-profile directory under profiles base: {Dir}", dir);
                continue;
            }

            try
            {
                var profile = ReadProfileFile(dir);
                summaries.Add(new ProfileSummary(id, profile.Name));
            }
            catch (Exception ex) when (ex is IOException or JsonException or UnauthorizedAccessException)
            {
                // A single unreadable profile must not break listing the rest.
                _logger.LogWarning(ex, "Skipping unreadable profile at {Dir}", dir);
            }
        }

        return summaries;
    }

    /// <inheritdoc />
    public Profile GetProfile(Guid id)
    {
        var dir = ProfileDir(id);
        return ReadProfileFile(dir); // throws KeyNotFoundException via EnsureReadable
    }

    /// <inheritdoc />
    public Profile CreateProfile(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            throw new ArgumentException("Profile name must not be null or whitespace.", nameof(name));
        }

        var profile = new Profile
        {
            Id = Guid.NewGuid(),
            Name = name,
            CreatedAt = DateTimeOffset.UtcNow,
            Mods = Array.Empty<ModListEntry>(),
        };

        // Scaffold the profile dir + mod root before persisting so a crash
        // between the two never leaves a profile.json without its mods/ dir.
        Directory.CreateDirectory(ProfileDir(profile.Id));
        Directory.CreateDirectory(ModRootDir(profile.Id));
        WriteProfileFile(profile);

        _logger.LogInformation("Created profile {Id} ('{Name}')", profile.Id, profile.Name);
        return profile;
    }

    /// <inheritdoc />
    public void RenameProfile(Guid id, string newName)
    {
        if (string.IsNullOrWhiteSpace(newName))
        {
            throw new ArgumentException("Profile name must not be null or whitespace.", nameof(newName));
        }

        var profile = GetProfile(id);
        var previous = profile.Name;
        profile.Name = newName;
        WriteProfileFile(profile);

        _logger.LogInformation("Renamed profile {Id} '{Previous}' -> '{Name}'", id, previous, newName);
    }

    /// <inheritdoc />
    public void DeleteProfile(Guid id)
    {
        var dir = ProfileDir(id);
        if (!Directory.Exists(dir))
        {
            throw UnknownProfile(id);
        }

        Directory.Delete(dir, recursive: true);
        _logger.LogInformation("Deleted profile {Id}", id);
    }

    /// <inheritdoc />
    public IReadOnlyList<ModListEntry> GetModList(Guid id) => GetProfile(id).Mods;

    /// <inheritdoc />
    public void SetModOrder(Guid id, IReadOnlyList<string> modNamesInOrder)
    {
        var profile = GetProfile(id);
        var current = profile.Mods;

        // Index the desired order by name (first occurrence wins for dupes).
        var desiredIndex = new Dictionary<string, int>(StringComparer.Ordinal);
        for (var i = 0; i < modNamesInOrder.Count; i++)
        {
            if (modNamesInOrder[i] is { Length: > 0 } n && !desiredIndex.ContainsKey(n))
            {
                desiredIndex[n] = i;
            }
        }

        // Stable sort: listed mods by their desired position first, then
        // unmentioned mods in their existing relative order. OrderBy is stable,
        // so equal keys keep storage order.
        var reordered = current
            .OrderBy(m => desiredIndex.TryGetValue(m.Name, out var idx) ? idx : int.MaxValue)
            .ToList();

        for (var i = 0; i < reordered.Count; i++)
        {
            reordered[i].Order = i;
        }

        profile.Mods = reordered;
        WriteProfileFile(profile);
    }

    /// <inheritdoc />
    public void SetModEnabled(Guid id, string modName, bool enabled)
    {
        var profile = GetProfile(id);
        var entry = profile.Mods.FirstOrDefault(m => string.Equals(m.Name, modName, StringComparison.Ordinal))
            ?? throw UnknownMod(id, modName);

        entry.Enabled = enabled;
        WriteProfileFile(profile);
    }

    /// <inheritdoc />
    public void AddMod(Guid id, string modName)
    {
        if (string.IsNullOrWhiteSpace(modName))
        {
            throw new ArgumentException("Mod name must not be null or whitespace.", nameof(modName));
        }

        var profile = GetProfile(id);

        // Idempotent: re-adding an existing mod is a no-op (keeps its order +
        // enabled state). Prevents duplicate entries from re-entrancy.
        if (profile.Mods.Any(m => string.Equals(m.Name, modName, StringComparison.Ordinal)))
        {
            return;
        }

        var nextOrder = profile.Mods.Count == 0 ? 0 : profile.Mods.Max(m => m.Order) + 1;
        var updated = profile.Mods.ToList();
        updated.Add(new ModListEntry { Name = modName, Enabled = true, Order = nextOrder });

        profile.Mods = updated;
        WriteProfileFile(profile);
    }

    /// <inheritdoc />
    public void RemoveMod(Guid id, string modName)
    {
        var profile = GetProfile(id);
        var entry = profile.Mods.FirstOrDefault(m => string.Equals(m.Name, modName, StringComparison.Ordinal))
            ?? throw UnknownMod(id, modName);

        var updated = profile.Mods.Where(m => !string.Equals(m.Name, modName, StringComparison.Ordinal)).ToList();
        profile.Mods = updated;
        WriteProfileFile(profile);

        // Best-effort directory cleanup: the mod's folder may legitimately not
        // exist (never installed, or already removed). Graceful, never throws.
        var modDir = Path.Combine(ModRootDir(id), modName);
        if (Directory.Exists(modDir))
        {
            try
            {
                Directory.Delete(modDir, recursive: true);
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
            {
                _logger.LogWarning(ex, "Could not remove mod directory for {Mod} on profile {Id}", modName, id);
            }
        }
    }

    /// <inheritdoc />
    public string PrepareModRoot(Guid id)
    {
        var profile = GetProfile(id);
        var modRoot = ModRootDir(id);
        Directory.CreateDirectory(modRoot);

        WriteModList(profile, modRoot);
        return modRoot;
    }

    // ---- mods.lst generation ------------------------------------------------

    private void WriteModList(Profile profile, string modRoot)
    {
        // Enabled mods only, in Order (stable sort preserves stored sequence
        // for tied Order values). Faithful to what's stored — no DMF-first
        // enforcement, no auto-sort (those are higher-layer concerns).
        var enabled = profile.Mods
            .Where(m => m.Enabled)
            .OrderBy(m => m.Order)
            .Select(m => m.Name);

        var sb = new StringBuilder();
        foreach (var name in enabled)
        {
            sb.Append(name).Append('\n');
        }

        File.WriteAllText(ModListPath(modRoot), sb.ToString(), ModListEncoding);
    }

    // ---- persistence helpers ------------------------------------------------

    private Profile ReadProfileFile(string profileDir)
    {
        var file = ProfileFilePath(profileDir);
        EnsureReadable(file, profileDir);
        using var stream = File.OpenRead(file);
        var profile = JsonSerializer.Deserialize<Profile>(stream) ?? new Profile();

        // System.Text.Json can leave a non-nullable property as null if the
        // file explicitly carries null (e.g. a hand-edit). Coerce Mods so
        // downstream enumeration never NRE.
        profile.Mods ??= Array.Empty<ModListEntry>();

        return profile;
    }

    private static void EnsureReadable(string file, string profileDir)
    {
        if (!Directory.Exists(profileDir) || !File.Exists(file))
        {
            throw new KeyNotFoundException($"No profile exists at '{profileDir}'.");
        }
    }

    private void WriteProfileFile(Profile profile)
    {
        var json = JsonSerializer.Serialize(profile, JsonOptions);
        File.WriteAllText(ProfileFilePath(ProfileDir(profile.Id)), json, ModListEncoding);
    }

    // ---- path helpers (all internal-only — never leak through the interface) --

    private string ProfileDir(Guid id) => Path.Combine(_baseFolder, id.ToString());
    private static string ProfileFilePath(string profileDir) => Path.Combine(profileDir, "profile.json");
    private string ModRootDir(Guid id) => Path.Combine(ProfileDir(id), "mods");
    private static string ModListPath(string modRoot) => Path.Combine(modRoot, "mods.lst");

    private static KeyNotFoundException UnknownProfile(Guid id) =>
        new($"No profile exists with id '{id}'.");

    private static KeyNotFoundException UnknownMod(Guid id, string modName) =>
        new($"Profile '{id}' has no mod named '{modName}'.");
}
