/* AUTO-GENERATED by tools/gen_stubs.py — DO NOT EDIT BY HAND. */
/* dbghelp proxy DLL: jump-thunk forwarders.
 *
 * This file contains:
 *   - definitions of the cached forwarder pointers (g_fwd_<NAME>)
 *   - the g_fwd_entries[] lookup table
 *   - one C forwarder function per export
 */

#include "stubs.h"

/* ---- Cached pointers (zero-initialized, populated by DllMain) --- */

FARPROC g_fwd_DbgHelpCreateUserDump = NULL;
FARPROC g_fwd_DbgHelpCreateUserDumpW = NULL;
FARPROC g_fwd_EnumDirTree = NULL;
FARPROC g_fwd_EnumDirTreeW = NULL;
FARPROC g_fwd_EnumerateLoadedModules = NULL;
FARPROC g_fwd_EnumerateLoadedModules64 = NULL;
FARPROC g_fwd_EnumerateLoadedModulesEx = NULL;
FARPROC g_fwd_EnumerateLoadedModulesExW = NULL;
FARPROC g_fwd_EnumerateLoadedModulesW64 = NULL;
FARPROC g_fwd_ExtensionApiVersion = NULL;
FARPROC g_fwd_FindDebugInfoFile = NULL;
FARPROC g_fwd_FindDebugInfoFileEx = NULL;
FARPROC g_fwd_FindDebugInfoFileExW = NULL;
FARPROC g_fwd_FindExecutableImage = NULL;
FARPROC g_fwd_FindExecutableImageEx = NULL;
FARPROC g_fwd_FindExecutableImageExW = NULL;
FARPROC g_fwd_FindFileInPath = NULL;
FARPROC g_fwd_FindFileInSearchPath = NULL;
FARPROC g_fwd_GetTimestampForLoadedLibrary = NULL;
FARPROC g_fwd_ImageDirectoryEntryToData = NULL;
FARPROC g_fwd_ImageDirectoryEntryToDataEx = NULL;
FARPROC g_fwd_ImageNtHeader = NULL;
FARPROC g_fwd_ImageRvaToSection = NULL;
FARPROC g_fwd_ImageRvaToVa = NULL;
FARPROC g_fwd_ImagehlpApiVersion = NULL;
FARPROC g_fwd_ImagehlpApiVersionEx = NULL;
FARPROC g_fwd_MakeSureDirectoryPathExists = NULL;
FARPROC g_fwd_MiniDumpReadDumpStream = NULL;
FARPROC g_fwd_MiniDumpWriteDump = NULL;
FARPROC g_fwd_SearchTreeForFile = NULL;
FARPROC g_fwd_SearchTreeForFileW = NULL;
FARPROC g_fwd_StackWalk = NULL;
FARPROC g_fwd_StackWalk64 = NULL;
FARPROC g_fwd_StackWalkEx = NULL;
FARPROC g_fwd_SymAddSourceStream = NULL;
FARPROC g_fwd_SymAddSourceStreamA = NULL;
FARPROC g_fwd_SymAddSourceStreamW = NULL;
FARPROC g_fwd_SymAddSymbol = NULL;
FARPROC g_fwd_SymAddSymbolW = NULL;
FARPROC g_fwd_SymAddrIncludeInlineTrace = NULL;
FARPROC g_fwd_SymCleanup = NULL;
FARPROC g_fwd_SymCompareInlineTrace = NULL;
FARPROC g_fwd_SymDeleteSymbol = NULL;
FARPROC g_fwd_SymDeleteSymbolW = NULL;
FARPROC g_fwd_SymEnumLines = NULL;
FARPROC g_fwd_SymEnumLinesW = NULL;
FARPROC g_fwd_SymEnumProcesses = NULL;
FARPROC g_fwd_SymEnumSourceFileTokens = NULL;
FARPROC g_fwd_SymEnumSourceFiles = NULL;
FARPROC g_fwd_SymEnumSourceFilesW = NULL;
FARPROC g_fwd_SymEnumSourceLines = NULL;
FARPROC g_fwd_SymEnumSourceLinesW = NULL;
FARPROC g_fwd_SymEnumSym = NULL;
FARPROC g_fwd_SymEnumSymbols = NULL;
FARPROC g_fwd_SymEnumSymbolsForAddr = NULL;
FARPROC g_fwd_SymEnumSymbolsForAddrW = NULL;
FARPROC g_fwd_SymEnumSymbolsW = NULL;
FARPROC g_fwd_SymEnumTypes = NULL;
FARPROC g_fwd_SymEnumTypesByName = NULL;
FARPROC g_fwd_SymEnumTypesByNameW = NULL;
FARPROC g_fwd_SymEnumTypesW = NULL;
FARPROC g_fwd_SymEnumerateModules = NULL;
FARPROC g_fwd_SymEnumerateModules64 = NULL;
FARPROC g_fwd_SymEnumerateModulesW64 = NULL;
FARPROC g_fwd_SymEnumerateSymbols = NULL;
FARPROC g_fwd_SymEnumerateSymbols64 = NULL;
FARPROC g_fwd_SymEnumerateSymbolsW = NULL;
FARPROC g_fwd_SymEnumerateSymbolsW64 = NULL;
FARPROC g_fwd_SymFindDebugInfoFile = NULL;
FARPROC g_fwd_SymFindDebugInfoFileW = NULL;
FARPROC g_fwd_SymFindExecutableImage = NULL;
FARPROC g_fwd_SymFindExecutableImageW = NULL;
FARPROC g_fwd_SymFindFileInPath = NULL;
FARPROC g_fwd_SymFindFileInPathW = NULL;
FARPROC g_fwd_SymFromAddr = NULL;
FARPROC g_fwd_SymFromAddrW = NULL;
FARPROC g_fwd_SymFromIndex = NULL;
FARPROC g_fwd_SymFromIndexW = NULL;
FARPROC g_fwd_SymFromInlineContext = NULL;
FARPROC g_fwd_SymFromInlineContextW = NULL;
FARPROC g_fwd_SymFromName = NULL;
FARPROC g_fwd_SymFromNameW = NULL;
FARPROC g_fwd_SymFromToken = NULL;
FARPROC g_fwd_SymFromTokenW = NULL;
FARPROC g_fwd_SymFunctionTableAccess = NULL;
FARPROC g_fwd_SymFunctionTableAccess64 = NULL;
FARPROC g_fwd_SymGetFileLineOffsets64 = NULL;
FARPROC g_fwd_SymGetHomeDirectory = NULL;
FARPROC g_fwd_SymGetHomeDirectoryW = NULL;
FARPROC g_fwd_SymGetExtendedOption = NULL;
FARPROC g_fwd_SymGetLineFromAddr = NULL;
FARPROC g_fwd_SymGetLineFromAddr64 = NULL;
FARPROC g_fwd_SymGetLineFromAddrW = NULL;
FARPROC g_fwd_SymGetLineFromAddrW64 = NULL;
FARPROC g_fwd_SymGetLineFromInlineContext = NULL;
FARPROC g_fwd_SymGetLineFromInlineContextW = NULL;
FARPROC g_fwd_SymGetLineFromName = NULL;
FARPROC g_fwd_SymGetLineFromName64 = NULL;
FARPROC g_fwd_SymGetLineFromNameW64 = NULL;
FARPROC g_fwd_SymGetLineNext = NULL;
FARPROC g_fwd_SymGetLineNext64 = NULL;
FARPROC g_fwd_SymGetLineNextW64 = NULL;
FARPROC g_fwd_SymGetLinePrev = NULL;
FARPROC g_fwd_SymGetLinePrev64 = NULL;
FARPROC g_fwd_SymGetLinePrevW64 = NULL;
FARPROC g_fwd_SymGetModuleBase = NULL;
FARPROC g_fwd_SymGetModuleBase64 = NULL;
FARPROC g_fwd_SymGetModuleInfo = NULL;
FARPROC g_fwd_SymGetModuleInfo64 = NULL;
FARPROC g_fwd_SymGetModuleInfoW = NULL;
FARPROC g_fwd_SymGetModuleInfoW64 = NULL;
FARPROC g_fwd_SymGetOmapBlockBase = NULL;
FARPROC g_fwd_SymGetOptions = NULL;
FARPROC g_fwd_SymGetScope = NULL;
FARPROC g_fwd_SymGetScopeW = NULL;
FARPROC g_fwd_SymGetSearchPath = NULL;
FARPROC g_fwd_SymGetSearchPathW = NULL;
FARPROC g_fwd_SymGetSourceFile = NULL;
FARPROC g_fwd_SymGetSourceFileFromToken = NULL;
FARPROC g_fwd_SymGetSourceFileFromTokenW = NULL;
FARPROC g_fwd_SymGetSourceFileToken = NULL;
FARPROC g_fwd_SymGetSourceFileTokenW = NULL;
FARPROC g_fwd_SymGetSourceFileW = NULL;
FARPROC g_fwd_SymGetSourceVarFromToken = NULL;
FARPROC g_fwd_SymGetSourceVarFromTokenW = NULL;
FARPROC g_fwd_SymGetSymFromAddr = NULL;
FARPROC g_fwd_SymGetSymFromAddr64 = NULL;
FARPROC g_fwd_SymGetSymFromName = NULL;
FARPROC g_fwd_SymGetSymFromName64 = NULL;
FARPROC g_fwd_SymGetSymNext = NULL;
FARPROC g_fwd_SymGetSymNext64 = NULL;
FARPROC g_fwd_SymGetSymPrev = NULL;
FARPROC g_fwd_SymGetSymPrev64 = NULL;
FARPROC g_fwd_SymGetSymbolFile = NULL;
FARPROC g_fwd_SymGetSymbolFileW = NULL;
FARPROC g_fwd_SymGetTypeFromName = NULL;
FARPROC g_fwd_SymGetTypeFromNameW = NULL;
FARPROC g_fwd_SymGetTypeInfo = NULL;
FARPROC g_fwd_SymGetTypeInfoEx = NULL;
FARPROC g_fwd_SymGetUnwindInfo = NULL;
FARPROC g_fwd_SymInitialize = NULL;
FARPROC g_fwd_SymInitializeW = NULL;
FARPROC g_fwd_SymLoadModule = NULL;
FARPROC g_fwd_SymLoadModule64 = NULL;
FARPROC g_fwd_SymLoadModuleEx = NULL;
FARPROC g_fwd_SymLoadModuleExW = NULL;
FARPROC g_fwd_SymMatchFileName = NULL;
FARPROC g_fwd_SymMatchFileNameW = NULL;
FARPROC g_fwd_SymMatchString = NULL;
FARPROC g_fwd_SymMatchStringA = NULL;
FARPROC g_fwd_SymMatchStringW = NULL;
FARPROC g_fwd_SymNext = NULL;
FARPROC g_fwd_SymNextW = NULL;
FARPROC g_fwd_SymPrev = NULL;
FARPROC g_fwd_SymPrevW = NULL;
FARPROC g_fwd_SymQueryInlineTrace = NULL;
FARPROC g_fwd_SymRefreshModuleList = NULL;
FARPROC g_fwd_SymRegisterCallback = NULL;
FARPROC g_fwd_SymRegisterCallback64 = NULL;
FARPROC g_fwd_SymRegisterCallbackW64 = NULL;
FARPROC g_fwd_SymRegisterFunctionEntryCallback = NULL;
FARPROC g_fwd_SymRegisterFunctionEntryCallback64 = NULL;
FARPROC g_fwd_SymSearch = NULL;
FARPROC g_fwd_SymSearchW = NULL;
FARPROC g_fwd_SymSetContext = NULL;
FARPROC g_fwd_SymSetExtendedOption = NULL;
FARPROC g_fwd_SymSetHomeDirectory = NULL;
FARPROC g_fwd_SymSetHomeDirectoryW = NULL;
FARPROC g_fwd_SymSetOptions = NULL;
FARPROC g_fwd_SymSetParentWindow = NULL;
FARPROC g_fwd_SymSetScopeFromAddr = NULL;
FARPROC g_fwd_SymSetScopeFromIndex = NULL;
FARPROC g_fwd_SymSetScopeFromInlineContext = NULL;
FARPROC g_fwd_SymSetSearchPath = NULL;
FARPROC g_fwd_SymSetSearchPathW = NULL;
FARPROC g_fwd_SymSrvDeltaName = NULL;
FARPROC g_fwd_SymSrvDeltaNameW = NULL;
FARPROC g_fwd_SymSrvGetFileIndexInfo = NULL;
FARPROC g_fwd_SymSrvGetFileIndexInfoW = NULL;
FARPROC g_fwd_SymSrvGetFileIndexString = NULL;
FARPROC g_fwd_SymSrvGetFileIndexStringW = NULL;
FARPROC g_fwd_SymSrvGetFileIndexes = NULL;
FARPROC g_fwd_SymSrvGetFileIndexesW = NULL;
FARPROC g_fwd_SymSrvGetSupplement = NULL;
FARPROC g_fwd_SymSrvGetSupplementW = NULL;
FARPROC g_fwd_SymSrvIsStore = NULL;
FARPROC g_fwd_SymSrvIsStoreW = NULL;
FARPROC g_fwd_SymSrvStoreFile = NULL;
FARPROC g_fwd_SymSrvStoreFileW = NULL;
FARPROC g_fwd_SymSrvStoreSupplement = NULL;
FARPROC g_fwd_SymSrvStoreSupplementW = NULL;
FARPROC g_fwd_SymSetSymWithAddr64 = NULL;
FARPROC g_fwd_SymUnDName = NULL;
FARPROC g_fwd_SymUnDName64 = NULL;
FARPROC g_fwd_SymUnloadModule = NULL;
FARPROC g_fwd_SymUnloadModule64 = NULL;
FARPROC g_fwd_UnDecorateSymbolName = NULL;
FARPROC g_fwd_UnDecorateSymbolNameW = NULL;
FARPROC g_fwd_WinDbgExtensionDllInit = NULL;
FARPROC g_fwd_wine_get_module_information = NULL;

/* ---- Lookup table for eager resolution in DllMain ---------- */

const struct fwd_entry g_fwd_entries[] = {
    {"DbgHelpCreateUserDump", &g_fwd_DbgHelpCreateUserDump},
    {"DbgHelpCreateUserDumpW", &g_fwd_DbgHelpCreateUserDumpW},
    {"EnumDirTree", &g_fwd_EnumDirTree},
    {"EnumDirTreeW", &g_fwd_EnumDirTreeW},
    {"EnumerateLoadedModules", &g_fwd_EnumerateLoadedModules},
    {"EnumerateLoadedModules64", &g_fwd_EnumerateLoadedModules64},
    {"EnumerateLoadedModulesEx", &g_fwd_EnumerateLoadedModulesEx},
    {"EnumerateLoadedModulesExW", &g_fwd_EnumerateLoadedModulesExW},
    {"EnumerateLoadedModulesW64", &g_fwd_EnumerateLoadedModulesW64},
    {"ExtensionApiVersion", &g_fwd_ExtensionApiVersion},
    {"FindDebugInfoFile", &g_fwd_FindDebugInfoFile},
    {"FindDebugInfoFileEx", &g_fwd_FindDebugInfoFileEx},
    {"FindDebugInfoFileExW", &g_fwd_FindDebugInfoFileExW},
    {"FindExecutableImage", &g_fwd_FindExecutableImage},
    {"FindExecutableImageEx", &g_fwd_FindExecutableImageEx},
    {"FindExecutableImageExW", &g_fwd_FindExecutableImageExW},
    {"FindFileInPath", &g_fwd_FindFileInPath},
    {"FindFileInSearchPath", &g_fwd_FindFileInSearchPath},
    {"GetTimestampForLoadedLibrary", &g_fwd_GetTimestampForLoadedLibrary},
    {"ImageDirectoryEntryToData", &g_fwd_ImageDirectoryEntryToData},
    {"ImageDirectoryEntryToDataEx", &g_fwd_ImageDirectoryEntryToDataEx},
    {"ImageNtHeader", &g_fwd_ImageNtHeader},
    {"ImageRvaToSection", &g_fwd_ImageRvaToSection},
    {"ImageRvaToVa", &g_fwd_ImageRvaToVa},
    {"ImagehlpApiVersion", &g_fwd_ImagehlpApiVersion},
    {"ImagehlpApiVersionEx", &g_fwd_ImagehlpApiVersionEx},
    {"MakeSureDirectoryPathExists", &g_fwd_MakeSureDirectoryPathExists},
    {"MiniDumpReadDumpStream", &g_fwd_MiniDumpReadDumpStream},
    {"MiniDumpWriteDump", &g_fwd_MiniDumpWriteDump},
    {"SearchTreeForFile", &g_fwd_SearchTreeForFile},
    {"SearchTreeForFileW", &g_fwd_SearchTreeForFileW},
    {"StackWalk", &g_fwd_StackWalk},
    {"StackWalk64", &g_fwd_StackWalk64},
    {"StackWalkEx", &g_fwd_StackWalkEx},
    {"SymAddSourceStream", &g_fwd_SymAddSourceStream},
    {"SymAddSourceStreamA", &g_fwd_SymAddSourceStreamA},
    {"SymAddSourceStreamW", &g_fwd_SymAddSourceStreamW},
    {"SymAddSymbol", &g_fwd_SymAddSymbol},
    {"SymAddSymbolW", &g_fwd_SymAddSymbolW},
    {"SymAddrIncludeInlineTrace", &g_fwd_SymAddrIncludeInlineTrace},
    {"SymCleanup", &g_fwd_SymCleanup},
    {"SymCompareInlineTrace", &g_fwd_SymCompareInlineTrace},
    {"SymDeleteSymbol", &g_fwd_SymDeleteSymbol},
    {"SymDeleteSymbolW", &g_fwd_SymDeleteSymbolW},
    {"SymEnumLines", &g_fwd_SymEnumLines},
    {"SymEnumLinesW", &g_fwd_SymEnumLinesW},
    {"SymEnumProcesses", &g_fwd_SymEnumProcesses},
    {"SymEnumSourceFileTokens", &g_fwd_SymEnumSourceFileTokens},
    {"SymEnumSourceFiles", &g_fwd_SymEnumSourceFiles},
    {"SymEnumSourceFilesW", &g_fwd_SymEnumSourceFilesW},
    {"SymEnumSourceLines", &g_fwd_SymEnumSourceLines},
    {"SymEnumSourceLinesW", &g_fwd_SymEnumSourceLinesW},
    {"SymEnumSym", &g_fwd_SymEnumSym},
    {"SymEnumSymbols", &g_fwd_SymEnumSymbols},
    {"SymEnumSymbolsForAddr", &g_fwd_SymEnumSymbolsForAddr},
    {"SymEnumSymbolsForAddrW", &g_fwd_SymEnumSymbolsForAddrW},
    {"SymEnumSymbolsW", &g_fwd_SymEnumSymbolsW},
    {"SymEnumTypes", &g_fwd_SymEnumTypes},
    {"SymEnumTypesByName", &g_fwd_SymEnumTypesByName},
    {"SymEnumTypesByNameW", &g_fwd_SymEnumTypesByNameW},
    {"SymEnumTypesW", &g_fwd_SymEnumTypesW},
    {"SymEnumerateModules", &g_fwd_SymEnumerateModules},
    {"SymEnumerateModules64", &g_fwd_SymEnumerateModules64},
    {"SymEnumerateModulesW64", &g_fwd_SymEnumerateModulesW64},
    {"SymEnumerateSymbols", &g_fwd_SymEnumerateSymbols},
    {"SymEnumerateSymbols64", &g_fwd_SymEnumerateSymbols64},
    {"SymEnumerateSymbolsW", &g_fwd_SymEnumerateSymbolsW},
    {"SymEnumerateSymbolsW64", &g_fwd_SymEnumerateSymbolsW64},
    {"SymFindDebugInfoFile", &g_fwd_SymFindDebugInfoFile},
    {"SymFindDebugInfoFileW", &g_fwd_SymFindDebugInfoFileW},
    {"SymFindExecutableImage", &g_fwd_SymFindExecutableImage},
    {"SymFindExecutableImageW", &g_fwd_SymFindExecutableImageW},
    {"SymFindFileInPath", &g_fwd_SymFindFileInPath},
    {"SymFindFileInPathW", &g_fwd_SymFindFileInPathW},
    {"SymFromAddr", &g_fwd_SymFromAddr},
    {"SymFromAddrW", &g_fwd_SymFromAddrW},
    {"SymFromIndex", &g_fwd_SymFromIndex},
    {"SymFromIndexW", &g_fwd_SymFromIndexW},
    {"SymFromInlineContext", &g_fwd_SymFromInlineContext},
    {"SymFromInlineContextW", &g_fwd_SymFromInlineContextW},
    {"SymFromName", &g_fwd_SymFromName},
    {"SymFromNameW", &g_fwd_SymFromNameW},
    {"SymFromToken", &g_fwd_SymFromToken},
    {"SymFromTokenW", &g_fwd_SymFromTokenW},
    {"SymFunctionTableAccess", &g_fwd_SymFunctionTableAccess},
    {"SymFunctionTableAccess64", &g_fwd_SymFunctionTableAccess64},
    {"SymGetFileLineOffsets64", &g_fwd_SymGetFileLineOffsets64},
    {"SymGetHomeDirectory", &g_fwd_SymGetHomeDirectory},
    {"SymGetHomeDirectoryW", &g_fwd_SymGetHomeDirectoryW},
    {"SymGetExtendedOption", &g_fwd_SymGetExtendedOption},
    {"SymGetLineFromAddr", &g_fwd_SymGetLineFromAddr},
    {"SymGetLineFromAddr64", &g_fwd_SymGetLineFromAddr64},
    {"SymGetLineFromAddrW", &g_fwd_SymGetLineFromAddrW},
    {"SymGetLineFromAddrW64", &g_fwd_SymGetLineFromAddrW64},
    {"SymGetLineFromInlineContext", &g_fwd_SymGetLineFromInlineContext},
    {"SymGetLineFromInlineContextW", &g_fwd_SymGetLineFromInlineContextW},
    {"SymGetLineFromName", &g_fwd_SymGetLineFromName},
    {"SymGetLineFromName64", &g_fwd_SymGetLineFromName64},
    {"SymGetLineFromNameW64", &g_fwd_SymGetLineFromNameW64},
    {"SymGetLineNext", &g_fwd_SymGetLineNext},
    {"SymGetLineNext64", &g_fwd_SymGetLineNext64},
    {"SymGetLineNextW64", &g_fwd_SymGetLineNextW64},
    {"SymGetLinePrev", &g_fwd_SymGetLinePrev},
    {"SymGetLinePrev64", &g_fwd_SymGetLinePrev64},
    {"SymGetLinePrevW64", &g_fwd_SymGetLinePrevW64},
    {"SymGetModuleBase", &g_fwd_SymGetModuleBase},
    {"SymGetModuleBase64", &g_fwd_SymGetModuleBase64},
    {"SymGetModuleInfo", &g_fwd_SymGetModuleInfo},
    {"SymGetModuleInfo64", &g_fwd_SymGetModuleInfo64},
    {"SymGetModuleInfoW", &g_fwd_SymGetModuleInfoW},
    {"SymGetModuleInfoW64", &g_fwd_SymGetModuleInfoW64},
    {"SymGetOmapBlockBase", &g_fwd_SymGetOmapBlockBase},
    {"SymGetOptions", &g_fwd_SymGetOptions},
    {"SymGetScope", &g_fwd_SymGetScope},
    {"SymGetScopeW", &g_fwd_SymGetScopeW},
    {"SymGetSearchPath", &g_fwd_SymGetSearchPath},
    {"SymGetSearchPathW", &g_fwd_SymGetSearchPathW},
    {"SymGetSourceFile", &g_fwd_SymGetSourceFile},
    {"SymGetSourceFileFromToken", &g_fwd_SymGetSourceFileFromToken},
    {"SymGetSourceFileFromTokenW", &g_fwd_SymGetSourceFileFromTokenW},
    {"SymGetSourceFileToken", &g_fwd_SymGetSourceFileToken},
    {"SymGetSourceFileTokenW", &g_fwd_SymGetSourceFileTokenW},
    {"SymGetSourceFileW", &g_fwd_SymGetSourceFileW},
    {"SymGetSourceVarFromToken", &g_fwd_SymGetSourceVarFromToken},
    {"SymGetSourceVarFromTokenW", &g_fwd_SymGetSourceVarFromTokenW},
    {"SymGetSymFromAddr", &g_fwd_SymGetSymFromAddr},
    {"SymGetSymFromAddr64", &g_fwd_SymGetSymFromAddr64},
    {"SymGetSymFromName", &g_fwd_SymGetSymFromName},
    {"SymGetSymFromName64", &g_fwd_SymGetSymFromName64},
    {"SymGetSymNext", &g_fwd_SymGetSymNext},
    {"SymGetSymNext64", &g_fwd_SymGetSymNext64},
    {"SymGetSymPrev", &g_fwd_SymGetSymPrev},
    {"SymGetSymPrev64", &g_fwd_SymGetSymPrev64},
    {"SymGetSymbolFile", &g_fwd_SymGetSymbolFile},
    {"SymGetSymbolFileW", &g_fwd_SymGetSymbolFileW},
    {"SymGetTypeFromName", &g_fwd_SymGetTypeFromName},
    {"SymGetTypeFromNameW", &g_fwd_SymGetTypeFromNameW},
    {"SymGetTypeInfo", &g_fwd_SymGetTypeInfo},
    {"SymGetTypeInfoEx", &g_fwd_SymGetTypeInfoEx},
    {"SymGetUnwindInfo", &g_fwd_SymGetUnwindInfo},
    {"SymInitialize", &g_fwd_SymInitialize},
    {"SymInitializeW", &g_fwd_SymInitializeW},
    {"SymLoadModule", &g_fwd_SymLoadModule},
    {"SymLoadModule64", &g_fwd_SymLoadModule64},
    {"SymLoadModuleEx", &g_fwd_SymLoadModuleEx},
    {"SymLoadModuleExW", &g_fwd_SymLoadModuleExW},
    {"SymMatchFileName", &g_fwd_SymMatchFileName},
    {"SymMatchFileNameW", &g_fwd_SymMatchFileNameW},
    {"SymMatchString", &g_fwd_SymMatchString},
    {"SymMatchStringA", &g_fwd_SymMatchStringA},
    {"SymMatchStringW", &g_fwd_SymMatchStringW},
    {"SymNext", &g_fwd_SymNext},
    {"SymNextW", &g_fwd_SymNextW},
    {"SymPrev", &g_fwd_SymPrev},
    {"SymPrevW", &g_fwd_SymPrevW},
    {"SymQueryInlineTrace", &g_fwd_SymQueryInlineTrace},
    {"SymRefreshModuleList", &g_fwd_SymRefreshModuleList},
    {"SymRegisterCallback", &g_fwd_SymRegisterCallback},
    {"SymRegisterCallback64", &g_fwd_SymRegisterCallback64},
    {"SymRegisterCallbackW64", &g_fwd_SymRegisterCallbackW64},
    {"SymRegisterFunctionEntryCallback", &g_fwd_SymRegisterFunctionEntryCallback},
    {"SymRegisterFunctionEntryCallback64", &g_fwd_SymRegisterFunctionEntryCallback64},
    {"SymSearch", &g_fwd_SymSearch},
    {"SymSearchW", &g_fwd_SymSearchW},
    {"SymSetContext", &g_fwd_SymSetContext},
    {"SymSetExtendedOption", &g_fwd_SymSetExtendedOption},
    {"SymSetHomeDirectory", &g_fwd_SymSetHomeDirectory},
    {"SymSetHomeDirectoryW", &g_fwd_SymSetHomeDirectoryW},
    {"SymSetOptions", &g_fwd_SymSetOptions},
    {"SymSetParentWindow", &g_fwd_SymSetParentWindow},
    {"SymSetScopeFromAddr", &g_fwd_SymSetScopeFromAddr},
    {"SymSetScopeFromIndex", &g_fwd_SymSetScopeFromIndex},
    {"SymSetScopeFromInlineContext", &g_fwd_SymSetScopeFromInlineContext},
    {"SymSetSearchPath", &g_fwd_SymSetSearchPath},
    {"SymSetSearchPathW", &g_fwd_SymSetSearchPathW},
    {"SymSrvDeltaName", &g_fwd_SymSrvDeltaName},
    {"SymSrvDeltaNameW", &g_fwd_SymSrvDeltaNameW},
    {"SymSrvGetFileIndexInfo", &g_fwd_SymSrvGetFileIndexInfo},
    {"SymSrvGetFileIndexInfoW", &g_fwd_SymSrvGetFileIndexInfoW},
    {"SymSrvGetFileIndexString", &g_fwd_SymSrvGetFileIndexString},
    {"SymSrvGetFileIndexStringW", &g_fwd_SymSrvGetFileIndexStringW},
    {"SymSrvGetFileIndexes", &g_fwd_SymSrvGetFileIndexes},
    {"SymSrvGetFileIndexesW", &g_fwd_SymSrvGetFileIndexesW},
    {"SymSrvGetSupplement", &g_fwd_SymSrvGetSupplement},
    {"SymSrvGetSupplementW", &g_fwd_SymSrvGetSupplementW},
    {"SymSrvIsStore", &g_fwd_SymSrvIsStore},
    {"SymSrvIsStoreW", &g_fwd_SymSrvIsStoreW},
    {"SymSrvStoreFile", &g_fwd_SymSrvStoreFile},
    {"SymSrvStoreFileW", &g_fwd_SymSrvStoreFileW},
    {"SymSrvStoreSupplement", &g_fwd_SymSrvStoreSupplement},
    {"SymSrvStoreSupplementW", &g_fwd_SymSrvStoreSupplementW},
    {"SymSetSymWithAddr64", &g_fwd_SymSetSymWithAddr64},
    {"SymUnDName", &g_fwd_SymUnDName},
    {"SymUnDName64", &g_fwd_SymUnDName64},
    {"SymUnloadModule", &g_fwd_SymUnloadModule},
    {"SymUnloadModule64", &g_fwd_SymUnloadModule64},
    {"UnDecorateSymbolName", &g_fwd_UnDecorateSymbolName},
    {"UnDecorateSymbolNameW", &g_fwd_UnDecorateSymbolNameW},
    {"WinDbgExtensionDllInit", &g_fwd_WinDbgExtensionDllInit},
    {"wine_get_module_information", &g_fwd_wine_get_module_information},
    {NULL, NULL},
};

/* ---- Forwarder functions ------------------------------------- */
/*
 * Fast path (cache hit):
 *     mov rax, [rip + g_fwd_<NAME>]
 *     test rax, rax
 *     jmp rax
 * Argument registers (RCX/RDX/R8/R9/XMM0-3) and shadow space
 * are untouched, so the forwarded function observes the
 * caller's original frame.
 */

void DbgHelpCreateUserDump(void) {
    FARPROC p = g_fwd_DbgHelpCreateUserDump;
    if (!p) p = g_fwd_DbgHelpCreateUserDump = fwd_resolve("DbgHelpCreateUserDump");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void DbgHelpCreateUserDumpW(void) {
    FARPROC p = g_fwd_DbgHelpCreateUserDumpW;
    if (!p) p = g_fwd_DbgHelpCreateUserDumpW = fwd_resolve("DbgHelpCreateUserDumpW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void EnumDirTree(void) {
    FARPROC p = g_fwd_EnumDirTree;
    if (!p) p = g_fwd_EnumDirTree = fwd_resolve("EnumDirTree");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void EnumDirTreeW(void) {
    FARPROC p = g_fwd_EnumDirTreeW;
    if (!p) p = g_fwd_EnumDirTreeW = fwd_resolve("EnumDirTreeW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void EnumerateLoadedModules(void) {
    FARPROC p = g_fwd_EnumerateLoadedModules;
    if (!p) p = g_fwd_EnumerateLoadedModules = fwd_resolve("EnumerateLoadedModules");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void EnumerateLoadedModules64(void) {
    FARPROC p = g_fwd_EnumerateLoadedModules64;
    if (!p) p = g_fwd_EnumerateLoadedModules64 = fwd_resolve("EnumerateLoadedModules64");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void EnumerateLoadedModulesEx(void) {
    FARPROC p = g_fwd_EnumerateLoadedModulesEx;
    if (!p) p = g_fwd_EnumerateLoadedModulesEx = fwd_resolve("EnumerateLoadedModulesEx");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void EnumerateLoadedModulesExW(void) {
    FARPROC p = g_fwd_EnumerateLoadedModulesExW;
    if (!p) p = g_fwd_EnumerateLoadedModulesExW = fwd_resolve("EnumerateLoadedModulesExW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void EnumerateLoadedModulesW64(void) {
    FARPROC p = g_fwd_EnumerateLoadedModulesW64;
    if (!p) p = g_fwd_EnumerateLoadedModulesW64 = fwd_resolve("EnumerateLoadedModulesW64");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void ExtensionApiVersion(void) {
    FARPROC p = g_fwd_ExtensionApiVersion;
    if (!p) p = g_fwd_ExtensionApiVersion = fwd_resolve("ExtensionApiVersion");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void FindDebugInfoFile(void) {
    FARPROC p = g_fwd_FindDebugInfoFile;
    if (!p) p = g_fwd_FindDebugInfoFile = fwd_resolve("FindDebugInfoFile");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void FindDebugInfoFileEx(void) {
    FARPROC p = g_fwd_FindDebugInfoFileEx;
    if (!p) p = g_fwd_FindDebugInfoFileEx = fwd_resolve("FindDebugInfoFileEx");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void FindDebugInfoFileExW(void) {
    FARPROC p = g_fwd_FindDebugInfoFileExW;
    if (!p) p = g_fwd_FindDebugInfoFileExW = fwd_resolve("FindDebugInfoFileExW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void FindExecutableImage(void) {
    FARPROC p = g_fwd_FindExecutableImage;
    if (!p) p = g_fwd_FindExecutableImage = fwd_resolve("FindExecutableImage");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void FindExecutableImageEx(void) {
    FARPROC p = g_fwd_FindExecutableImageEx;
    if (!p) p = g_fwd_FindExecutableImageEx = fwd_resolve("FindExecutableImageEx");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void FindExecutableImageExW(void) {
    FARPROC p = g_fwd_FindExecutableImageExW;
    if (!p) p = g_fwd_FindExecutableImageExW = fwd_resolve("FindExecutableImageExW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void FindFileInPath(void) {
    FARPROC p = g_fwd_FindFileInPath;
    if (!p) p = g_fwd_FindFileInPath = fwd_resolve("FindFileInPath");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void FindFileInSearchPath(void) {
    FARPROC p = g_fwd_FindFileInSearchPath;
    if (!p) p = g_fwd_FindFileInSearchPath = fwd_resolve("FindFileInSearchPath");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void GetTimestampForLoadedLibrary(void) {
    FARPROC p = g_fwd_GetTimestampForLoadedLibrary;
    if (!p) p = g_fwd_GetTimestampForLoadedLibrary = fwd_resolve("GetTimestampForLoadedLibrary");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void ImageDirectoryEntryToData(void) {
    FARPROC p = g_fwd_ImageDirectoryEntryToData;
    if (!p) p = g_fwd_ImageDirectoryEntryToData = fwd_resolve("ImageDirectoryEntryToData");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void ImageDirectoryEntryToDataEx(void) {
    FARPROC p = g_fwd_ImageDirectoryEntryToDataEx;
    if (!p) p = g_fwd_ImageDirectoryEntryToDataEx = fwd_resolve("ImageDirectoryEntryToDataEx");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void ImageNtHeader(void) {
    FARPROC p = g_fwd_ImageNtHeader;
    if (!p) p = g_fwd_ImageNtHeader = fwd_resolve("ImageNtHeader");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void ImageRvaToSection(void) {
    FARPROC p = g_fwd_ImageRvaToSection;
    if (!p) p = g_fwd_ImageRvaToSection = fwd_resolve("ImageRvaToSection");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void ImageRvaToVa(void) {
    FARPROC p = g_fwd_ImageRvaToVa;
    if (!p) p = g_fwd_ImageRvaToVa = fwd_resolve("ImageRvaToVa");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void ImagehlpApiVersion(void) {
    FARPROC p = g_fwd_ImagehlpApiVersion;
    if (!p) p = g_fwd_ImagehlpApiVersion = fwd_resolve("ImagehlpApiVersion");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void ImagehlpApiVersionEx(void) {
    FARPROC p = g_fwd_ImagehlpApiVersionEx;
    if (!p) p = g_fwd_ImagehlpApiVersionEx = fwd_resolve("ImagehlpApiVersionEx");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void MakeSureDirectoryPathExists(void) {
    FARPROC p = g_fwd_MakeSureDirectoryPathExists;
    if (!p) p = g_fwd_MakeSureDirectoryPathExists = fwd_resolve("MakeSureDirectoryPathExists");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void MiniDumpReadDumpStream(void) {
    FARPROC p = g_fwd_MiniDumpReadDumpStream;
    if (!p) p = g_fwd_MiniDumpReadDumpStream = fwd_resolve("MiniDumpReadDumpStream");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void MiniDumpWriteDump(void) {
    FARPROC p = g_fwd_MiniDumpWriteDump;
    if (!p) p = g_fwd_MiniDumpWriteDump = fwd_resolve("MiniDumpWriteDump");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SearchTreeForFile(void) {
    FARPROC p = g_fwd_SearchTreeForFile;
    if (!p) p = g_fwd_SearchTreeForFile = fwd_resolve("SearchTreeForFile");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SearchTreeForFileW(void) {
    FARPROC p = g_fwd_SearchTreeForFileW;
    if (!p) p = g_fwd_SearchTreeForFileW = fwd_resolve("SearchTreeForFileW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void StackWalk(void) {
    FARPROC p = g_fwd_StackWalk;
    if (!p) p = g_fwd_StackWalk = fwd_resolve("StackWalk");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void StackWalk64(void) {
    FARPROC p = g_fwd_StackWalk64;
    if (!p) p = g_fwd_StackWalk64 = fwd_resolve("StackWalk64");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void StackWalkEx(void) {
    FARPROC p = g_fwd_StackWalkEx;
    if (!p) p = g_fwd_StackWalkEx = fwd_resolve("StackWalkEx");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymAddSourceStream(void) {
    FARPROC p = g_fwd_SymAddSourceStream;
    if (!p) p = g_fwd_SymAddSourceStream = fwd_resolve("SymAddSourceStream");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymAddSourceStreamA(void) {
    FARPROC p = g_fwd_SymAddSourceStreamA;
    if (!p) p = g_fwd_SymAddSourceStreamA = fwd_resolve("SymAddSourceStreamA");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymAddSourceStreamW(void) {
    FARPROC p = g_fwd_SymAddSourceStreamW;
    if (!p) p = g_fwd_SymAddSourceStreamW = fwd_resolve("SymAddSourceStreamW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymAddSymbol(void) {
    FARPROC p = g_fwd_SymAddSymbol;
    if (!p) p = g_fwd_SymAddSymbol = fwd_resolve("SymAddSymbol");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymAddSymbolW(void) {
    FARPROC p = g_fwd_SymAddSymbolW;
    if (!p) p = g_fwd_SymAddSymbolW = fwd_resolve("SymAddSymbolW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymAddrIncludeInlineTrace(void) {
    FARPROC p = g_fwd_SymAddrIncludeInlineTrace;
    if (!p) p = g_fwd_SymAddrIncludeInlineTrace = fwd_resolve("SymAddrIncludeInlineTrace");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymCleanup(void) {
    FARPROC p = g_fwd_SymCleanup;
    if (!p) p = g_fwd_SymCleanup = fwd_resolve("SymCleanup");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymCompareInlineTrace(void) {
    FARPROC p = g_fwd_SymCompareInlineTrace;
    if (!p) p = g_fwd_SymCompareInlineTrace = fwd_resolve("SymCompareInlineTrace");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymDeleteSymbol(void) {
    FARPROC p = g_fwd_SymDeleteSymbol;
    if (!p) p = g_fwd_SymDeleteSymbol = fwd_resolve("SymDeleteSymbol");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymDeleteSymbolW(void) {
    FARPROC p = g_fwd_SymDeleteSymbolW;
    if (!p) p = g_fwd_SymDeleteSymbolW = fwd_resolve("SymDeleteSymbolW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymEnumLines(void) {
    FARPROC p = g_fwd_SymEnumLines;
    if (!p) p = g_fwd_SymEnumLines = fwd_resolve("SymEnumLines");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymEnumLinesW(void) {
    FARPROC p = g_fwd_SymEnumLinesW;
    if (!p) p = g_fwd_SymEnumLinesW = fwd_resolve("SymEnumLinesW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymEnumProcesses(void) {
    FARPROC p = g_fwd_SymEnumProcesses;
    if (!p) p = g_fwd_SymEnumProcesses = fwd_resolve("SymEnumProcesses");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymEnumSourceFileTokens(void) {
    FARPROC p = g_fwd_SymEnumSourceFileTokens;
    if (!p) p = g_fwd_SymEnumSourceFileTokens = fwd_resolve("SymEnumSourceFileTokens");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymEnumSourceFiles(void) {
    FARPROC p = g_fwd_SymEnumSourceFiles;
    if (!p) p = g_fwd_SymEnumSourceFiles = fwd_resolve("SymEnumSourceFiles");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymEnumSourceFilesW(void) {
    FARPROC p = g_fwd_SymEnumSourceFilesW;
    if (!p) p = g_fwd_SymEnumSourceFilesW = fwd_resolve("SymEnumSourceFilesW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymEnumSourceLines(void) {
    FARPROC p = g_fwd_SymEnumSourceLines;
    if (!p) p = g_fwd_SymEnumSourceLines = fwd_resolve("SymEnumSourceLines");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymEnumSourceLinesW(void) {
    FARPROC p = g_fwd_SymEnumSourceLinesW;
    if (!p) p = g_fwd_SymEnumSourceLinesW = fwd_resolve("SymEnumSourceLinesW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymEnumSym(void) {
    FARPROC p = g_fwd_SymEnumSym;
    if (!p) p = g_fwd_SymEnumSym = fwd_resolve("SymEnumSym");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymEnumSymbols(void) {
    FARPROC p = g_fwd_SymEnumSymbols;
    if (!p) p = g_fwd_SymEnumSymbols = fwd_resolve("SymEnumSymbols");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymEnumSymbolsForAddr(void) {
    FARPROC p = g_fwd_SymEnumSymbolsForAddr;
    if (!p) p = g_fwd_SymEnumSymbolsForAddr = fwd_resolve("SymEnumSymbolsForAddr");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymEnumSymbolsForAddrW(void) {
    FARPROC p = g_fwd_SymEnumSymbolsForAddrW;
    if (!p) p = g_fwd_SymEnumSymbolsForAddrW = fwd_resolve("SymEnumSymbolsForAddrW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymEnumSymbolsW(void) {
    FARPROC p = g_fwd_SymEnumSymbolsW;
    if (!p) p = g_fwd_SymEnumSymbolsW = fwd_resolve("SymEnumSymbolsW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymEnumTypes(void) {
    FARPROC p = g_fwd_SymEnumTypes;
    if (!p) p = g_fwd_SymEnumTypes = fwd_resolve("SymEnumTypes");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymEnumTypesByName(void) {
    FARPROC p = g_fwd_SymEnumTypesByName;
    if (!p) p = g_fwd_SymEnumTypesByName = fwd_resolve("SymEnumTypesByName");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymEnumTypesByNameW(void) {
    FARPROC p = g_fwd_SymEnumTypesByNameW;
    if (!p) p = g_fwd_SymEnumTypesByNameW = fwd_resolve("SymEnumTypesByNameW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymEnumTypesW(void) {
    FARPROC p = g_fwd_SymEnumTypesW;
    if (!p) p = g_fwd_SymEnumTypesW = fwd_resolve("SymEnumTypesW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymEnumerateModules(void) {
    FARPROC p = g_fwd_SymEnumerateModules;
    if (!p) p = g_fwd_SymEnumerateModules = fwd_resolve("SymEnumerateModules");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymEnumerateModules64(void) {
    FARPROC p = g_fwd_SymEnumerateModules64;
    if (!p) p = g_fwd_SymEnumerateModules64 = fwd_resolve("SymEnumerateModules64");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymEnumerateModulesW64(void) {
    FARPROC p = g_fwd_SymEnumerateModulesW64;
    if (!p) p = g_fwd_SymEnumerateModulesW64 = fwd_resolve("SymEnumerateModulesW64");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymEnumerateSymbols(void) {
    FARPROC p = g_fwd_SymEnumerateSymbols;
    if (!p) p = g_fwd_SymEnumerateSymbols = fwd_resolve("SymEnumerateSymbols");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymEnumerateSymbols64(void) {
    FARPROC p = g_fwd_SymEnumerateSymbols64;
    if (!p) p = g_fwd_SymEnumerateSymbols64 = fwd_resolve("SymEnumerateSymbols64");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymEnumerateSymbolsW(void) {
    FARPROC p = g_fwd_SymEnumerateSymbolsW;
    if (!p) p = g_fwd_SymEnumerateSymbolsW = fwd_resolve("SymEnumerateSymbolsW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymEnumerateSymbolsW64(void) {
    FARPROC p = g_fwd_SymEnumerateSymbolsW64;
    if (!p) p = g_fwd_SymEnumerateSymbolsW64 = fwd_resolve("SymEnumerateSymbolsW64");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymFindDebugInfoFile(void) {
    FARPROC p = g_fwd_SymFindDebugInfoFile;
    if (!p) p = g_fwd_SymFindDebugInfoFile = fwd_resolve("SymFindDebugInfoFile");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymFindDebugInfoFileW(void) {
    FARPROC p = g_fwd_SymFindDebugInfoFileW;
    if (!p) p = g_fwd_SymFindDebugInfoFileW = fwd_resolve("SymFindDebugInfoFileW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymFindExecutableImage(void) {
    FARPROC p = g_fwd_SymFindExecutableImage;
    if (!p) p = g_fwd_SymFindExecutableImage = fwd_resolve("SymFindExecutableImage");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymFindExecutableImageW(void) {
    FARPROC p = g_fwd_SymFindExecutableImageW;
    if (!p) p = g_fwd_SymFindExecutableImageW = fwd_resolve("SymFindExecutableImageW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymFindFileInPath(void) {
    FARPROC p = g_fwd_SymFindFileInPath;
    if (!p) p = g_fwd_SymFindFileInPath = fwd_resolve("SymFindFileInPath");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymFindFileInPathW(void) {
    FARPROC p = g_fwd_SymFindFileInPathW;
    if (!p) p = g_fwd_SymFindFileInPathW = fwd_resolve("SymFindFileInPathW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymFromAddr(void) {
    FARPROC p = g_fwd_SymFromAddr;
    if (!p) p = g_fwd_SymFromAddr = fwd_resolve("SymFromAddr");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymFromAddrW(void) {
    FARPROC p = g_fwd_SymFromAddrW;
    if (!p) p = g_fwd_SymFromAddrW = fwd_resolve("SymFromAddrW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymFromIndex(void) {
    FARPROC p = g_fwd_SymFromIndex;
    if (!p) p = g_fwd_SymFromIndex = fwd_resolve("SymFromIndex");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymFromIndexW(void) {
    FARPROC p = g_fwd_SymFromIndexW;
    if (!p) p = g_fwd_SymFromIndexW = fwd_resolve("SymFromIndexW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymFromInlineContext(void) {
    FARPROC p = g_fwd_SymFromInlineContext;
    if (!p) p = g_fwd_SymFromInlineContext = fwd_resolve("SymFromInlineContext");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymFromInlineContextW(void) {
    FARPROC p = g_fwd_SymFromInlineContextW;
    if (!p) p = g_fwd_SymFromInlineContextW = fwd_resolve("SymFromInlineContextW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymFromName(void) {
    FARPROC p = g_fwd_SymFromName;
    if (!p) p = g_fwd_SymFromName = fwd_resolve("SymFromName");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymFromNameW(void) {
    FARPROC p = g_fwd_SymFromNameW;
    if (!p) p = g_fwd_SymFromNameW = fwd_resolve("SymFromNameW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymFromToken(void) {
    FARPROC p = g_fwd_SymFromToken;
    if (!p) p = g_fwd_SymFromToken = fwd_resolve("SymFromToken");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymFromTokenW(void) {
    FARPROC p = g_fwd_SymFromTokenW;
    if (!p) p = g_fwd_SymFromTokenW = fwd_resolve("SymFromTokenW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymFunctionTableAccess(void) {
    FARPROC p = g_fwd_SymFunctionTableAccess;
    if (!p) p = g_fwd_SymFunctionTableAccess = fwd_resolve("SymFunctionTableAccess");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymFunctionTableAccess64(void) {
    FARPROC p = g_fwd_SymFunctionTableAccess64;
    if (!p) p = g_fwd_SymFunctionTableAccess64 = fwd_resolve("SymFunctionTableAccess64");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetFileLineOffsets64(void) {
    FARPROC p = g_fwd_SymGetFileLineOffsets64;
    if (!p) p = g_fwd_SymGetFileLineOffsets64 = fwd_resolve("SymGetFileLineOffsets64");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetHomeDirectory(void) {
    FARPROC p = g_fwd_SymGetHomeDirectory;
    if (!p) p = g_fwd_SymGetHomeDirectory = fwd_resolve("SymGetHomeDirectory");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetHomeDirectoryW(void) {
    FARPROC p = g_fwd_SymGetHomeDirectoryW;
    if (!p) p = g_fwd_SymGetHomeDirectoryW = fwd_resolve("SymGetHomeDirectoryW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetExtendedOption(void) {
    FARPROC p = g_fwd_SymGetExtendedOption;
    if (!p) p = g_fwd_SymGetExtendedOption = fwd_resolve("SymGetExtendedOption");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetLineFromAddr(void) {
    FARPROC p = g_fwd_SymGetLineFromAddr;
    if (!p) p = g_fwd_SymGetLineFromAddr = fwd_resolve("SymGetLineFromAddr");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetLineFromAddr64(void) {
    FARPROC p = g_fwd_SymGetLineFromAddr64;
    if (!p) p = g_fwd_SymGetLineFromAddr64 = fwd_resolve("SymGetLineFromAddr64");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetLineFromAddrW(void) {
    FARPROC p = g_fwd_SymGetLineFromAddrW;
    if (!p) p = g_fwd_SymGetLineFromAddrW = fwd_resolve("SymGetLineFromAddrW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetLineFromAddrW64(void) {
    FARPROC p = g_fwd_SymGetLineFromAddrW64;
    if (!p) p = g_fwd_SymGetLineFromAddrW64 = fwd_resolve("SymGetLineFromAddrW64");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetLineFromInlineContext(void) {
    FARPROC p = g_fwd_SymGetLineFromInlineContext;
    if (!p) p = g_fwd_SymGetLineFromInlineContext = fwd_resolve("SymGetLineFromInlineContext");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetLineFromInlineContextW(void) {
    FARPROC p = g_fwd_SymGetLineFromInlineContextW;
    if (!p) p = g_fwd_SymGetLineFromInlineContextW = fwd_resolve("SymGetLineFromInlineContextW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetLineFromName(void) {
    FARPROC p = g_fwd_SymGetLineFromName;
    if (!p) p = g_fwd_SymGetLineFromName = fwd_resolve("SymGetLineFromName");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetLineFromName64(void) {
    FARPROC p = g_fwd_SymGetLineFromName64;
    if (!p) p = g_fwd_SymGetLineFromName64 = fwd_resolve("SymGetLineFromName64");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetLineFromNameW64(void) {
    FARPROC p = g_fwd_SymGetLineFromNameW64;
    if (!p) p = g_fwd_SymGetLineFromNameW64 = fwd_resolve("SymGetLineFromNameW64");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetLineNext(void) {
    FARPROC p = g_fwd_SymGetLineNext;
    if (!p) p = g_fwd_SymGetLineNext = fwd_resolve("SymGetLineNext");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetLineNext64(void) {
    FARPROC p = g_fwd_SymGetLineNext64;
    if (!p) p = g_fwd_SymGetLineNext64 = fwd_resolve("SymGetLineNext64");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetLineNextW64(void) {
    FARPROC p = g_fwd_SymGetLineNextW64;
    if (!p) p = g_fwd_SymGetLineNextW64 = fwd_resolve("SymGetLineNextW64");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetLinePrev(void) {
    FARPROC p = g_fwd_SymGetLinePrev;
    if (!p) p = g_fwd_SymGetLinePrev = fwd_resolve("SymGetLinePrev");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetLinePrev64(void) {
    FARPROC p = g_fwd_SymGetLinePrev64;
    if (!p) p = g_fwd_SymGetLinePrev64 = fwd_resolve("SymGetLinePrev64");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetLinePrevW64(void) {
    FARPROC p = g_fwd_SymGetLinePrevW64;
    if (!p) p = g_fwd_SymGetLinePrevW64 = fwd_resolve("SymGetLinePrevW64");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetModuleBase(void) {
    FARPROC p = g_fwd_SymGetModuleBase;
    if (!p) p = g_fwd_SymGetModuleBase = fwd_resolve("SymGetModuleBase");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetModuleBase64(void) {
    FARPROC p = g_fwd_SymGetModuleBase64;
    if (!p) p = g_fwd_SymGetModuleBase64 = fwd_resolve("SymGetModuleBase64");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetModuleInfo(void) {
    FARPROC p = g_fwd_SymGetModuleInfo;
    if (!p) p = g_fwd_SymGetModuleInfo = fwd_resolve("SymGetModuleInfo");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetModuleInfo64(void) {
    FARPROC p = g_fwd_SymGetModuleInfo64;
    if (!p) p = g_fwd_SymGetModuleInfo64 = fwd_resolve("SymGetModuleInfo64");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetModuleInfoW(void) {
    FARPROC p = g_fwd_SymGetModuleInfoW;
    if (!p) p = g_fwd_SymGetModuleInfoW = fwd_resolve("SymGetModuleInfoW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetModuleInfoW64(void) {
    FARPROC p = g_fwd_SymGetModuleInfoW64;
    if (!p) p = g_fwd_SymGetModuleInfoW64 = fwd_resolve("SymGetModuleInfoW64");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetOmapBlockBase(void) {
    FARPROC p = g_fwd_SymGetOmapBlockBase;
    if (!p) p = g_fwd_SymGetOmapBlockBase = fwd_resolve("SymGetOmapBlockBase");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetOptions(void) {
    FARPROC p = g_fwd_SymGetOptions;
    if (!p) p = g_fwd_SymGetOptions = fwd_resolve("SymGetOptions");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetScope(void) {
    FARPROC p = g_fwd_SymGetScope;
    if (!p) p = g_fwd_SymGetScope = fwd_resolve("SymGetScope");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetScopeW(void) {
    FARPROC p = g_fwd_SymGetScopeW;
    if (!p) p = g_fwd_SymGetScopeW = fwd_resolve("SymGetScopeW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetSearchPath(void) {
    FARPROC p = g_fwd_SymGetSearchPath;
    if (!p) p = g_fwd_SymGetSearchPath = fwd_resolve("SymGetSearchPath");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetSearchPathW(void) {
    FARPROC p = g_fwd_SymGetSearchPathW;
    if (!p) p = g_fwd_SymGetSearchPathW = fwd_resolve("SymGetSearchPathW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetSourceFile(void) {
    FARPROC p = g_fwd_SymGetSourceFile;
    if (!p) p = g_fwd_SymGetSourceFile = fwd_resolve("SymGetSourceFile");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetSourceFileFromToken(void) {
    FARPROC p = g_fwd_SymGetSourceFileFromToken;
    if (!p) p = g_fwd_SymGetSourceFileFromToken = fwd_resolve("SymGetSourceFileFromToken");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetSourceFileFromTokenW(void) {
    FARPROC p = g_fwd_SymGetSourceFileFromTokenW;
    if (!p) p = g_fwd_SymGetSourceFileFromTokenW = fwd_resolve("SymGetSourceFileFromTokenW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetSourceFileToken(void) {
    FARPROC p = g_fwd_SymGetSourceFileToken;
    if (!p) p = g_fwd_SymGetSourceFileToken = fwd_resolve("SymGetSourceFileToken");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetSourceFileTokenW(void) {
    FARPROC p = g_fwd_SymGetSourceFileTokenW;
    if (!p) p = g_fwd_SymGetSourceFileTokenW = fwd_resolve("SymGetSourceFileTokenW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetSourceFileW(void) {
    FARPROC p = g_fwd_SymGetSourceFileW;
    if (!p) p = g_fwd_SymGetSourceFileW = fwd_resolve("SymGetSourceFileW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetSourceVarFromToken(void) {
    FARPROC p = g_fwd_SymGetSourceVarFromToken;
    if (!p) p = g_fwd_SymGetSourceVarFromToken = fwd_resolve("SymGetSourceVarFromToken");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetSourceVarFromTokenW(void) {
    FARPROC p = g_fwd_SymGetSourceVarFromTokenW;
    if (!p) p = g_fwd_SymGetSourceVarFromTokenW = fwd_resolve("SymGetSourceVarFromTokenW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetSymFromAddr(void) {
    FARPROC p = g_fwd_SymGetSymFromAddr;
    if (!p) p = g_fwd_SymGetSymFromAddr = fwd_resolve("SymGetSymFromAddr");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetSymFromAddr64(void) {
    FARPROC p = g_fwd_SymGetSymFromAddr64;
    if (!p) p = g_fwd_SymGetSymFromAddr64 = fwd_resolve("SymGetSymFromAddr64");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetSymFromName(void) {
    FARPROC p = g_fwd_SymGetSymFromName;
    if (!p) p = g_fwd_SymGetSymFromName = fwd_resolve("SymGetSymFromName");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetSymFromName64(void) {
    FARPROC p = g_fwd_SymGetSymFromName64;
    if (!p) p = g_fwd_SymGetSymFromName64 = fwd_resolve("SymGetSymFromName64");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetSymNext(void) {
    FARPROC p = g_fwd_SymGetSymNext;
    if (!p) p = g_fwd_SymGetSymNext = fwd_resolve("SymGetSymNext");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetSymNext64(void) {
    FARPROC p = g_fwd_SymGetSymNext64;
    if (!p) p = g_fwd_SymGetSymNext64 = fwd_resolve("SymGetSymNext64");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetSymPrev(void) {
    FARPROC p = g_fwd_SymGetSymPrev;
    if (!p) p = g_fwd_SymGetSymPrev = fwd_resolve("SymGetSymPrev");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetSymPrev64(void) {
    FARPROC p = g_fwd_SymGetSymPrev64;
    if (!p) p = g_fwd_SymGetSymPrev64 = fwd_resolve("SymGetSymPrev64");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetSymbolFile(void) {
    FARPROC p = g_fwd_SymGetSymbolFile;
    if (!p) p = g_fwd_SymGetSymbolFile = fwd_resolve("SymGetSymbolFile");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetSymbolFileW(void) {
    FARPROC p = g_fwd_SymGetSymbolFileW;
    if (!p) p = g_fwd_SymGetSymbolFileW = fwd_resolve("SymGetSymbolFileW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetTypeFromName(void) {
    FARPROC p = g_fwd_SymGetTypeFromName;
    if (!p) p = g_fwd_SymGetTypeFromName = fwd_resolve("SymGetTypeFromName");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetTypeFromNameW(void) {
    FARPROC p = g_fwd_SymGetTypeFromNameW;
    if (!p) p = g_fwd_SymGetTypeFromNameW = fwd_resolve("SymGetTypeFromNameW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetTypeInfo(void) {
    FARPROC p = g_fwd_SymGetTypeInfo;
    if (!p) p = g_fwd_SymGetTypeInfo = fwd_resolve("SymGetTypeInfo");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetTypeInfoEx(void) {
    FARPROC p = g_fwd_SymGetTypeInfoEx;
    if (!p) p = g_fwd_SymGetTypeInfoEx = fwd_resolve("SymGetTypeInfoEx");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymGetUnwindInfo(void) {
    FARPROC p = g_fwd_SymGetUnwindInfo;
    if (!p) p = g_fwd_SymGetUnwindInfo = fwd_resolve("SymGetUnwindInfo");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymInitialize(void) {
    FARPROC p = g_fwd_SymInitialize;
    if (!p) p = g_fwd_SymInitialize = fwd_resolve("SymInitialize");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymInitializeW(void) {
    FARPROC p = g_fwd_SymInitializeW;
    if (!p) p = g_fwd_SymInitializeW = fwd_resolve("SymInitializeW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymLoadModule(void) {
    FARPROC p = g_fwd_SymLoadModule;
    if (!p) p = g_fwd_SymLoadModule = fwd_resolve("SymLoadModule");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymLoadModule64(void) {
    FARPROC p = g_fwd_SymLoadModule64;
    if (!p) p = g_fwd_SymLoadModule64 = fwd_resolve("SymLoadModule64");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymLoadModuleEx(void) {
    FARPROC p = g_fwd_SymLoadModuleEx;
    if (!p) p = g_fwd_SymLoadModuleEx = fwd_resolve("SymLoadModuleEx");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymLoadModuleExW(void) {
    FARPROC p = g_fwd_SymLoadModuleExW;
    if (!p) p = g_fwd_SymLoadModuleExW = fwd_resolve("SymLoadModuleExW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymMatchFileName(void) {
    FARPROC p = g_fwd_SymMatchFileName;
    if (!p) p = g_fwd_SymMatchFileName = fwd_resolve("SymMatchFileName");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymMatchFileNameW(void) {
    FARPROC p = g_fwd_SymMatchFileNameW;
    if (!p) p = g_fwd_SymMatchFileNameW = fwd_resolve("SymMatchFileNameW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymMatchString(void) {
    FARPROC p = g_fwd_SymMatchString;
    if (!p) p = g_fwd_SymMatchString = fwd_resolve("SymMatchString");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymMatchStringA(void) {
    FARPROC p = g_fwd_SymMatchStringA;
    if (!p) p = g_fwd_SymMatchStringA = fwd_resolve("SymMatchStringA");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymMatchStringW(void) {
    FARPROC p = g_fwd_SymMatchStringW;
    if (!p) p = g_fwd_SymMatchStringW = fwd_resolve("SymMatchStringW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymNext(void) {
    FARPROC p = g_fwd_SymNext;
    if (!p) p = g_fwd_SymNext = fwd_resolve("SymNext");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymNextW(void) {
    FARPROC p = g_fwd_SymNextW;
    if (!p) p = g_fwd_SymNextW = fwd_resolve("SymNextW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymPrev(void) {
    FARPROC p = g_fwd_SymPrev;
    if (!p) p = g_fwd_SymPrev = fwd_resolve("SymPrev");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymPrevW(void) {
    FARPROC p = g_fwd_SymPrevW;
    if (!p) p = g_fwd_SymPrevW = fwd_resolve("SymPrevW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymQueryInlineTrace(void) {
    FARPROC p = g_fwd_SymQueryInlineTrace;
    if (!p) p = g_fwd_SymQueryInlineTrace = fwd_resolve("SymQueryInlineTrace");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymRefreshModuleList(void) {
    FARPROC p = g_fwd_SymRefreshModuleList;
    if (!p) p = g_fwd_SymRefreshModuleList = fwd_resolve("SymRefreshModuleList");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymRegisterCallback(void) {
    FARPROC p = g_fwd_SymRegisterCallback;
    if (!p) p = g_fwd_SymRegisterCallback = fwd_resolve("SymRegisterCallback");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymRegisterCallback64(void) {
    FARPROC p = g_fwd_SymRegisterCallback64;
    if (!p) p = g_fwd_SymRegisterCallback64 = fwd_resolve("SymRegisterCallback64");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymRegisterCallbackW64(void) {
    FARPROC p = g_fwd_SymRegisterCallbackW64;
    if (!p) p = g_fwd_SymRegisterCallbackW64 = fwd_resolve("SymRegisterCallbackW64");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymRegisterFunctionEntryCallback(void) {
    FARPROC p = g_fwd_SymRegisterFunctionEntryCallback;
    if (!p) p = g_fwd_SymRegisterFunctionEntryCallback = fwd_resolve("SymRegisterFunctionEntryCallback");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymRegisterFunctionEntryCallback64(void) {
    FARPROC p = g_fwd_SymRegisterFunctionEntryCallback64;
    if (!p) p = g_fwd_SymRegisterFunctionEntryCallback64 = fwd_resolve("SymRegisterFunctionEntryCallback64");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymSearch(void) {
    FARPROC p = g_fwd_SymSearch;
    if (!p) p = g_fwd_SymSearch = fwd_resolve("SymSearch");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymSearchW(void) {
    FARPROC p = g_fwd_SymSearchW;
    if (!p) p = g_fwd_SymSearchW = fwd_resolve("SymSearchW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymSetContext(void) {
    FARPROC p = g_fwd_SymSetContext;
    if (!p) p = g_fwd_SymSetContext = fwd_resolve("SymSetContext");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymSetExtendedOption(void) {
    FARPROC p = g_fwd_SymSetExtendedOption;
    if (!p) p = g_fwd_SymSetExtendedOption = fwd_resolve("SymSetExtendedOption");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymSetHomeDirectory(void) {
    FARPROC p = g_fwd_SymSetHomeDirectory;
    if (!p) p = g_fwd_SymSetHomeDirectory = fwd_resolve("SymSetHomeDirectory");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymSetHomeDirectoryW(void) {
    FARPROC p = g_fwd_SymSetHomeDirectoryW;
    if (!p) p = g_fwd_SymSetHomeDirectoryW = fwd_resolve("SymSetHomeDirectoryW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymSetOptions(void) {
    FARPROC p = g_fwd_SymSetOptions;
    if (!p) p = g_fwd_SymSetOptions = fwd_resolve("SymSetOptions");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymSetParentWindow(void) {
    FARPROC p = g_fwd_SymSetParentWindow;
    if (!p) p = g_fwd_SymSetParentWindow = fwd_resolve("SymSetParentWindow");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymSetScopeFromAddr(void) {
    FARPROC p = g_fwd_SymSetScopeFromAddr;
    if (!p) p = g_fwd_SymSetScopeFromAddr = fwd_resolve("SymSetScopeFromAddr");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymSetScopeFromIndex(void) {
    FARPROC p = g_fwd_SymSetScopeFromIndex;
    if (!p) p = g_fwd_SymSetScopeFromIndex = fwd_resolve("SymSetScopeFromIndex");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymSetScopeFromInlineContext(void) {
    FARPROC p = g_fwd_SymSetScopeFromInlineContext;
    if (!p) p = g_fwd_SymSetScopeFromInlineContext = fwd_resolve("SymSetScopeFromInlineContext");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymSetSearchPath(void) {
    FARPROC p = g_fwd_SymSetSearchPath;
    if (!p) p = g_fwd_SymSetSearchPath = fwd_resolve("SymSetSearchPath");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymSetSearchPathW(void) {
    FARPROC p = g_fwd_SymSetSearchPathW;
    if (!p) p = g_fwd_SymSetSearchPathW = fwd_resolve("SymSetSearchPathW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymSrvDeltaName(void) {
    FARPROC p = g_fwd_SymSrvDeltaName;
    if (!p) p = g_fwd_SymSrvDeltaName = fwd_resolve("SymSrvDeltaName");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymSrvDeltaNameW(void) {
    FARPROC p = g_fwd_SymSrvDeltaNameW;
    if (!p) p = g_fwd_SymSrvDeltaNameW = fwd_resolve("SymSrvDeltaNameW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymSrvGetFileIndexInfo(void) {
    FARPROC p = g_fwd_SymSrvGetFileIndexInfo;
    if (!p) p = g_fwd_SymSrvGetFileIndexInfo = fwd_resolve("SymSrvGetFileIndexInfo");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymSrvGetFileIndexInfoW(void) {
    FARPROC p = g_fwd_SymSrvGetFileIndexInfoW;
    if (!p) p = g_fwd_SymSrvGetFileIndexInfoW = fwd_resolve("SymSrvGetFileIndexInfoW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymSrvGetFileIndexString(void) {
    FARPROC p = g_fwd_SymSrvGetFileIndexString;
    if (!p) p = g_fwd_SymSrvGetFileIndexString = fwd_resolve("SymSrvGetFileIndexString");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymSrvGetFileIndexStringW(void) {
    FARPROC p = g_fwd_SymSrvGetFileIndexStringW;
    if (!p) p = g_fwd_SymSrvGetFileIndexStringW = fwd_resolve("SymSrvGetFileIndexStringW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymSrvGetFileIndexes(void) {
    FARPROC p = g_fwd_SymSrvGetFileIndexes;
    if (!p) p = g_fwd_SymSrvGetFileIndexes = fwd_resolve("SymSrvGetFileIndexes");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymSrvGetFileIndexesW(void) {
    FARPROC p = g_fwd_SymSrvGetFileIndexesW;
    if (!p) p = g_fwd_SymSrvGetFileIndexesW = fwd_resolve("SymSrvGetFileIndexesW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymSrvGetSupplement(void) {
    FARPROC p = g_fwd_SymSrvGetSupplement;
    if (!p) p = g_fwd_SymSrvGetSupplement = fwd_resolve("SymSrvGetSupplement");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymSrvGetSupplementW(void) {
    FARPROC p = g_fwd_SymSrvGetSupplementW;
    if (!p) p = g_fwd_SymSrvGetSupplementW = fwd_resolve("SymSrvGetSupplementW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymSrvIsStore(void) {
    FARPROC p = g_fwd_SymSrvIsStore;
    if (!p) p = g_fwd_SymSrvIsStore = fwd_resolve("SymSrvIsStore");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymSrvIsStoreW(void) {
    FARPROC p = g_fwd_SymSrvIsStoreW;
    if (!p) p = g_fwd_SymSrvIsStoreW = fwd_resolve("SymSrvIsStoreW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymSrvStoreFile(void) {
    FARPROC p = g_fwd_SymSrvStoreFile;
    if (!p) p = g_fwd_SymSrvStoreFile = fwd_resolve("SymSrvStoreFile");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymSrvStoreFileW(void) {
    FARPROC p = g_fwd_SymSrvStoreFileW;
    if (!p) p = g_fwd_SymSrvStoreFileW = fwd_resolve("SymSrvStoreFileW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymSrvStoreSupplement(void) {
    FARPROC p = g_fwd_SymSrvStoreSupplement;
    if (!p) p = g_fwd_SymSrvStoreSupplement = fwd_resolve("SymSrvStoreSupplement");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymSrvStoreSupplementW(void) {
    FARPROC p = g_fwd_SymSrvStoreSupplementW;
    if (!p) p = g_fwd_SymSrvStoreSupplementW = fwd_resolve("SymSrvStoreSupplementW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymSetSymWithAddr64(void) {
    FARPROC p = g_fwd_SymSetSymWithAddr64;
    if (!p) p = g_fwd_SymSetSymWithAddr64 = fwd_resolve("SymSetSymWithAddr64");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymUnDName(void) {
    FARPROC p = g_fwd_SymUnDName;
    if (!p) p = g_fwd_SymUnDName = fwd_resolve("SymUnDName");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymUnDName64(void) {
    FARPROC p = g_fwd_SymUnDName64;
    if (!p) p = g_fwd_SymUnDName64 = fwd_resolve("SymUnDName64");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymUnloadModule(void) {
    FARPROC p = g_fwd_SymUnloadModule;
    if (!p) p = g_fwd_SymUnloadModule = fwd_resolve("SymUnloadModule");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void SymUnloadModule64(void) {
    FARPROC p = g_fwd_SymUnloadModule64;
    if (!p) p = g_fwd_SymUnloadModule64 = fwd_resolve("SymUnloadModule64");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void UnDecorateSymbolName(void) {
    FARPROC p = g_fwd_UnDecorateSymbolName;
    if (!p) p = g_fwd_UnDecorateSymbolName = fwd_resolve("UnDecorateSymbolName");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void UnDecorateSymbolNameW(void) {
    FARPROC p = g_fwd_UnDecorateSymbolNameW;
    if (!p) p = g_fwd_UnDecorateSymbolNameW = fwd_resolve("UnDecorateSymbolNameW");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void WinDbgExtensionDllInit(void) {
    FARPROC p = g_fwd_WinDbgExtensionDllInit;
    if (!p) p = g_fwd_WinDbgExtensionDllInit = fwd_resolve("WinDbgExtensionDllInit");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}

void wine_get_module_information(void) {
    FARPROC p = g_fwd_wine_get_module_information;
    if (!p) p = g_fwd_wine_get_module_information = fwd_resolve("wine_get_module_information");
    if (!p) return;  /* real dbghelp missing this export */
    ((void(*)(void))p)();
}
